name: Build and push

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
      - name: Get the tag
        id: get_image_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      # NOTE: this step is necessary because otherwise the build-push-action can't push /o\
      #       https://github.com/docker/build-push-action/issues/100#issuecomment-715352826
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            eurodatacube/eodash-dashboard-api:${{ steps.get_image_tag.outputs.TAG }}

      - name: test and push
        run: |
          IMG="eurodatacube/eodash-dashboard-api:${{ steps.get_image_tag.outputs.TAG }}"
          docker run --env-file test_environment.env "${IMG}" pytest || exit 1
          docker run "${IMG}" flake8 || exit 1
          docker run "${IMG}" mypy . || exit 1
          docker push "${IMG}"
